install.packages("RPostgreSQL", repos='http://cran.us.r-project.org')
install.packages("dplyr", repos='http://cran.us.r-project.org')
install.packages("dbplyr", repos='http://cran.us.r-project.org')
install.packages("tidyr", repos='http://cran.us.r-project.org')
install.packages("lubridate", repos='http://cran.us.r-project.org')
install.packages("stringr", repos='http://cran.us.r-project.org')
install.packages("feather", repos='http://cran.us.r-project.org')
install.packages("readr", repos='http://cran.us.r-project.org')
